package com.huan.mapper;

import com.huan.model.TPermission;

import java.util.List;

public interface TPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    int insert(TPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    TPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    List<TPermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    int updateByPrimaryKey(TPermission record);
}