package com.huan.mapper;

import com.huan.model.TRole;

import java.util.List;

public interface TRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    int insert(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    TRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    List<TRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    int updateByPrimaryKey(TRole record);
}