package com.huan.mapper;

import com.huan.model.TUserRole;

import java.util.List;

public interface TUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    int insert(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    List<TUserRole> selectAll();
}