package com.huan.model;

public class TPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.permissionname
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    private String permissionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.role_id
     *
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.permissionname
     *
     * @return the value of t_permission.permissionname
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.permissionname
     *
     * @param permissionname the value for t_permission.permissionname
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.role_id
     *
     * @return the value of t_permission.role_id
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.role_id
     *
     * @param roleId the value for t_permission.role_id
     * @mbggenerated Fri Jul 15 01:30:17 CST 2016
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}