package com.huan.model;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.cover_photo
     *
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    private String coverPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.cover_photo
     *
     * @return the value of post.cover_photo
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public String getCoverPhoto() {
        return coverPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.cover_photo
     *
     * @param coverPhoto the value for post.cover_photo
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public void setCoverPhoto(String coverPhoto) {
        this.coverPhoto = coverPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     * @mbggenerated Thu Jun 23 23:12:42 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }
}